AdPages = ['Allianz Australia', 'Red Rooster', 'Alice's Garden', 'Penfolds', 
           'Commonwealth Bank', 'PetCloud', 'Newstead Brewing Co.', 'Mercurian Media', 
           'Taubmans Australia', 'Auswise Pest Control', 'Tony Abbott', 
           'Clean Air Conditioning', 'Lendi.com.au', 'Croc Gold Traps', 
           'Adam Wildman Gold Coast Videographer', 'Brisbane Festival', 
           'Treasury Casino and Hotel', 'Lisa Wilkinson', 'Channel 9', 'TODAY', 
           'Woolworths', 'AAMI', 'Education Changemakers', 'Getter', 'ANZ Australia', 
           'M.J. Bale', 'Queensland Health', 'Golf Australia', 'T.M.Lewin', 'RedBalloon', 
           'Fiverr', 'Work and Training Solutions', 'MYER', 'Out of the Box Physiotherapy', 
           'YWS', 'Rouse Realty', 'Latina Fresh Australia', 'Lowes Australia', 
           'Al Rigato - Ray White', 'Australian Bananas', 'Streets Ice Cream', 
           'Zyrtec Australia', 'Cleveland Caravan, Camping, Boating & 4x4 Expo', 
           'Air New Zealand', 'Yates Gardening', 'Adobe After Effects', 'Chiko', 
           'Good vision for life', 'First Choice Chiropractic', 'Stay Strong PT', 
           'Lottoland Australia', 'Doo-Bop Jazz Bar', 'Dental Members Australia', 
           'HD Lawyers', 'VIRUS Action Sport Performance - Aust.', 
           'Mercedes-Benz Australia', 'StreamSend', 'KIRIN', 'AMS Mt Buller', 
           'Roughchop Bicycle Adventures', 'NuStrength', 'Aveda', 'Luxland', 
           'Wakebbb XSport Store', 'NRMA Insurance', 'Brisbane Alfa Romeo', 'Ontraport', 
           'StoreFormula', 'Mosaic Property Group', 'FritzenbergerBNE', 'Quit Job to Write', 
           'Comparethemarket.com.au', 'Black Series Campers & Caravans', 'GT AUTOS', 
           'Mercedes-Benz Brisbane', 'Brisbane Pain Rehabilitation Service - BPRS', 
           'Clandestine Design Group', '7-Eleven Australia', 'Aquamint Laboratories, Inc.', 
           'Big Night Out', 'Building Block Studio', 'Invictus 5', 'Spotify', 
           'Tony Burke MP', 'Hey, It's OK - Things Do get B E T T E R.', 'SEEK', 
           'Haymans Lighting and Design Centre - The Valley.', 
           'James Gwynne Team - Harcourts Solutions', 'Tomas Mian Ray White', 
           'Success Tax Professionals', 'Profit with Bitcoin', 'Presentation Sells', 
           '4Cabling', 'Bestjet.com', 'Nissan 4x4 Australia', 'Billykart West End', 
           'Sony Pictures', 'Yeppoon Electrical And Solar', 'Harrison Human Resources', 
           'Rod Lingard Home Loan Connexion', 'Altitude Finance', 'ropelace', 'Gobbler', 
           'Todd P.', 'Suunto', 'Get Your Biz Found', 'finder.com.au', 'Fusccars', 
           'Preferred Car Care Brisbane', 'It's Mirchi Healthy Indian', 'Advantage First', 
           'Elite Fitness Equipment Virginia', 'The Working Holiday Club', 
           'Lapont Language Centre', 'Great Big Story', 'Zambrero', 'Lexus Australia', 
           'Anne Edmonds.', 'Sohal Living', 'Aston Milan', 'PointsBet', 'St.George Bank', 
           'Multicultural Queensland - MDA', 'Luxury Properties Brisbane - Denis Najzar', 
           'realestate.com.au/news', 'Goodstart Early Learning', 'Keno', 
           'Revolutionary Real Estate', 'G1 Asset Management', 'Butler+Co Estate Agents', 
           'My Next Loan & My Next Car', 'Lonely Planet', 
           'Fox Home Entertainment AU – Access All Areas', 'Real Insurance', 'CodeMakers', 
           'Michel Pépé - Fans Club', 'Middleton Park', 'Expose Media Group', 
           'QUT Law Students', 'Zno', 'Xero', 'Lifestyle Lily', 'iNode Cloud', 
           'JAFX - Trusted True ECN Forex Broker', 'Telstra', 'Social Media Mastery', 
           'Apple', 'Chamber of Commerce & Industry Queensland', 'Unibet', 'Peer Estate', 
           'Be Coyote', 'YourCountdown.To', 'Xsolla', 'Point Hacks', 'Specsavers Australia', 
           'Mighty Car Mods', '4WDSupacentre.com.au', 'Semi Permanent', 'Shape Collage', 
           'NBN Australia', 'Canstar', 'Samsonite Australia & New Zealand', 
           'CA Technologies', 'ASUS', 'Coles', 'Kia Australia', 
           'Canadian Wilderness Adventures', 'Bendigo Bank Telco', 'Jollys U Pull It', 
           'Dan Murphy's', 'Youfoodz', 'Mission Australia', 'OnDeck', 'freedom australia', 
           'Kinderling Kids Radio', 'Hit105', 'Alinta Energy', 
           'The Athlete's Foot Australia', 'Fix-A-Tap', 'Southern Downs and Granite Belt', 
           'Jameson Irish Whiskey', 'Roadshow', 'Liquid Web', 'Visit NSW', 'Secret Wood', 
           'Impulse Rehab Centre', 'GearBest Shopping', 
           'Sunlighten Australia & New Zealand', 
           'Wilson's Group - Air Conditioning & Refrigeration', '100% Pure New Zealand', 
           'Lateral Event Management', 'Virgin Mobile Australia', 'Pitchblak', 'KitKat', 
           'Cellarbrations', 'The University of Queensland Faculty of Science', 'Nuzzel', 
           'Bento With Love', 'Appleton Estate', 'Pariya', 'Lipton', 'Carpet Court', 
           'Dr Charles Cope', '88rising', 'KFC', 'Pack My Product', 'Visa', 
           'Mazda Australia', 'Clive Palmer', 'BIG W', 'Cosmos Magazine', 
           'Creative Investment Solutions', 'Guidelight Psychology & Wellness', 
           'The Scarlet Singapore', 'Munns', 'Opera Australia', 'Von Bibra Auto Village', 
           'Kultured Wellness', 'The Fabric Frieze', 'EnergyAustralia', 'Surface', 
           'BuzzFeed Australia', 'Magnum', 'Cinch Digital', 'ArtsHub', 
           'The Heart of Universal Business', 'The Urban List | Brisbane', 
           'Metro South Health', 'Microsoft Store', 'Roadworthy Hero', 'Guardian Labs', 
           'Industry Super', 'North Queensland Toyota Cowboys', 'Australia Zoo', 'AirAsia', 
           'Motor Trades Association of Queensland - MTAQ', 'Trevor Evans MP', 
           'Cruising Excursions', 'Scrum On', 'Blue Dolphin Marine Tours', 'Pizza Capers', 
           'Cycling, Tour Down Under', 'Australian Unions', 'GoDaddy', 
           'Santos: Australia's Energy Company', 'Brisbane PTE Study Centre', 
           'Start-up-Guide.com', 'Foss Electrical', 'Shared', 'Audi Centre Brisbane', 
           'Office', 'TAFE Queensland', 'Evapolar', 'MATLAB', 'Men's Health', 'AMP Capital', 
           'South Australia', 'GO Creative', 'Cubebrush', 'Swarmify', 'EB Pearls', 
           '1Tac.com', 'GROW Super', 'Cenovis Australia', 'Australian Eggs', 
           'Centrepoint Alliance', 'Key Person of Influence', 'Dean Property Team', 
           'Prospa', 'Crystal Blue Yacht Charters', 'Fast', 
           'Jesse James - Harcourts Solutions', 'Noble and Jones', 'BMW Australia', 
           'Family Home Experts', 'Always Dry Australia', 'Pointcorp Development', 
           'Coles Express', 'Takeflight', 'Ben Wakely Properties', 'Bynder', 
           'Smith's Lawyers', 'Fitstop West End', 'Nintendo', 'Berocca Australia', 
           'Hoyts Australia', 'Sam Prosser - Place Real Estate', 'Sunny The Egg', 
           'Lilydale - Living Free Range', 'Brown Brothers Winery', 'eBay.com.au', 
           'Alfa Romeo Australia', 'Grow Consulting Group', 'Madd Loans', 'Hallmark Homes', 
           'Game of Thrones - EU', 'JD Lighting & Home Decor', 'One Click Away', 
           'The PICA Group', 'Mad Bookie', 'Boost Mobile Australia', 'OnePlus', 'BRICKX', 
           'X-Drive Australia', 'MLC Australia', 'Project-Mu Australia', 'Qantas', 
           'De'Longhi Australia', 'Social Estate', 'Samsung SmartLife', 
           'Queen's Wharf Brisbane', 'Chemdry Active - Carpet and Upholstery Cleaning', 
           'Square', 'Bentley Brisbane', 'Neto', 
           'Professional Photographers Insurance Brokers', 'Bundaberg Rum', 'Strea.ma', 
           'MYOB', 'Airtasker', 'Honey', 'Apex DIY Training', 'Medibank', 
           'Jump Swim Schools Bellbowrie', 'Wotif.com', 'Lenovo', 'Purina Australia', 
           'Bojan Zimmermann', 'HoneyBadger', 'Gucci', 'Rudolphonline', 'Subway Australia', 
           'Uniqlo Australia', 'DHA Invest', 'UAV Me', 
           'C&K - The Creche & Kindergarten Association Limited', 'CareSuper', '9GAG TV', 
           'Your Hot Property', 'Business Legal Lifecycle', 'Broli', 'M&M'S Australia', 
           'JS Watch co. Reykjavik', 'OPSM', 'Lift and Load', 'JUCY', 'Cu Sq.', 
           'Little Brixton', 'AppSumo', 'The Discipline of Innovation', 'Deliveroo', 
           'I Love Real Estate', 'True Local', 'Electronic Living', 'Innovic', 
           'Hudson Plumbers', 'Beachsea Brisbane', 'McDonald's', 'Fitness Institute', 
           'Magic Car Clean inc. Brisbane Paint Protection', 
           'Amazon Prime Video Australia & New Zealand', 'Foxtel', '20th Century Fox', 
           'Alex Jordan - McGrath Estate Agents', 'StudioPress', 
           'Bree-elle Independent Arbonne Consultant', 'WorkflowMax', 'Get Tools Direct', 
           'iZotope', 'MG Motor Australia', 'Blue Air & Electrical', 'Stan.', 
           'Coles Financial Services', 'Taboola', 'Getflix', 'Samsung Australia', 
           'Battery World', '7 News Adelaide', 'Allen's Lollies', 'Saint Laurent', 
           'Canon Australia', 'Magshop Australia', 'ClickFunnels', 'Meeum', 'Freedom360', 
           'Kenwood', 'Mount Gravatt Mazda', 'Vision Potential', 
           'Aquarius Refrigeration & Air Conditioning.', 'TruWood', 'Koala', 
           'H&R Block Australia', 'Coca-Cola Australia', 'Intel', 'Right Property Group', 
           'flybuys', 'Wealthrite - Financial Services', 'Personal Injury in Australia', 
           'Toyota Australia', 'Shane Gerekink - LJ Hooker Paddington', 
           'Woolworths Rewards', 'MoneyQuest - Mermaid Waters', 'Shopify', 'IKEA', 'UBET', 
           'FXCM Australia', 'Suncorp', 'Financial Review', 'easyMarkets', 
           'Reclaim Health and Rehab', 'Prism Venture Group', 'Motorola', 
           'Lenovo Australia and New Zealand', 'IL Molo Italian Kitchen & Bar', 
           'Brookwater Golf & Country Club', 'King Kong Co.', 'Position Property', 
           'HashChing', 'Rentalvalue.com.au', 'HSBC', 'Ladbrokes.com.au', 'BforB Australia', 
           'Youi', 'Wix', 'Office for Businesses', 'Squadhelp', 'Tigerair Australia', 
           'Grammarly', 'Rich Training', 'Atlant Real Estate Platform', 'Moneyball.com.au', 
           'BFGoodrich Tires', 'Thrive Property', 
           'FPA - Financial Planning Association of Australia', 'Udemy', 'Open Colleges', 
           'Forge of Empires', 'Basic Bananas', 'Authentic Education', 'American Express', 
           'George & King', 'Squarespace', 'Infusionsoft', 'HearingPlanet', 'Asana', 
           'Hotjar', 'Australian Ethical Super', 'InspireCycle', 'Eden Gold Coast', 
           'Royal Caribbean International', 'Voyage Financial', 'LG Australia', 'XXXX GOLD', 
           'Codral', 'Golden Circle', 'Bupa Australia', 'Holden', 'EA Games - Asia Pacific', 
           'Porsche', 'LEGO']
